# Generated by Django 5.0.6 on 2024-06-08 22:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, null=True)),
                ('telemovel', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, null=True)),
                ('tempo', models.IntegerField(null=True)),
                ('obs', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('km', models.IntegerField()),
                ('ano', models.DateField(null=True)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='servicos_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=260, null=True)),
                ('data_entrada', models.DateField(default=datetime.datetime.now)),
                ('hora_entrada', models.DateTimeField(default=datetime.datetime.now)),
                ('data_saida', models.DateField(default=datetime.datetime.now)),
                ('hora_saida', models.DateTimeField(default=datetime.datetime.now)),
                ('servicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.servicos')),
                ('veiculos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.veiculos')),
            ],
        ),
    ]
