# Generated by Django 5.0.6 on 2024-06-11 10:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, null=True)),
                ('telem', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.datetime.now)),
                ('start_hour', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('end_hour', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, null=True)),
                ('time', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='InfoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onGoing', models.BooleanField(default=False)),
                ('startDate', models.DateField(default=datetime.datetime.now)),
                ('finishDate', models.DateField(default=datetime.datetime.now)),
                ('totalTime', models.DateField(default=datetime.datetime.now)),
                ('idEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.event')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.service')),
                ('idTechnician', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='service_api.technician')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='idType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.tipology'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('km', models.IntegerField()),
                ('year', models.DateField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.client')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.vehicle'),
        ),
    ]
