# Generated by Django 5.0.6 on 2024-06-11 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoservice',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='infoservice',
            name='startDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='infoservice',
            name='totalTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
