# Generated by Django 5.0.6 on 2024-06-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0003_alter_infoservice_finishdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
