# Generated by Django 5.0.6 on 2024-06-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0005_event_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoservice',
            name='onGoing',
            field=models.CharField(choices=[('1', 'por iniciar'), ('2', 'a decorrer'), ('3', 'Terminado')], default=1, max_length=180),
        ),
    ]
