# Generated by Django 5.0.6 on 2024-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0006_alter_infoservice_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoservice',
            name='totalTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
