# Generated by Django 5.0.6 on 2024-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0007_alter_infoservice_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoservice',
            name='totalTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
